export const WEATHER = {
  "Nhiều mây" : {value: 'Nhiều mây', label: 'hãy ra ngoài đi dạo và thư giãn nhé !'},
  "Nắng": {value: 'Nắng', label: 'nhớ phải mang theo ô hoặc áo chống nắng khi ra ngoài nhé !'},
  Clear: {value: 'Clear', label: 'hãy ra ngoài đi dạo và thư giãn nhé !'},
}

export const HELLO = {
  1: "Xin chào {0}! Hôm nay {0} cảm thấy thế nào?",
  2: "Xin chào, Tib-chan hy vọng {0} đã có một ngày tuyệt vời!",
  3: "Chào {0}, {0} đã cảm thấy hứng khởi về điều gì hôm nay chưa?",
  4: "Xin chào {0}! {0} đã thưởng thức những điều tốt lành của ngày hôm nay chưa?",
  5: "Chào {0}, Tib-chan mong {0} đã bắt đầu ngày mới với năng lượng đầy đủ!",
  6: "Xin chào, cảm ơn {0} đã ghé qua. Có điều gì tuyệt vời xảy ra không?",
  7: "Chào {0}, Tib-chan hy vọng {0} đã bắt đầu ngày mới với một nụ cười!",
  8: "Xin chào {0}! Hãy cho Tib-chan biết {0} đã có ý tưởng gì cho ngày hôm nay chưa?",
  9: "Chào {0}, cảm ơn {0} đã đến! Có điều gì đặc biệt xảy ra trong tuần của {0} không?",
  10: "Xin chào! Hãy kể cho Tib-chan nghe điều thú vị nhất {0} đã trải qua trong thời gian qua.",
  11: "Chào {0}, hôm nay {0} đã tự thưởng cho mình điều gì chưa?",
  12: "Chào {0}, mọi thứ đã diễn ra như {0} mong đợi chưa?",
  13: "Xin chào! Hãy cho Tib-chan biết {0} đã có kế hoạch gì cho cuối tuần sắp tới chưa?",
  14: "Chào {0}, Tib-chan hy vọng {0} đã có một ngày thú vị và đầy ý nghĩa!",
  15: "Xin chào {0}! Hãy kể Tib-chan nghe điều vui vẻ nhất {0} đã trải qua hôm nay.",
  16: "Chào {0}, {0} đã làm điều gì để nâng cao tinh thần của {0} hôm nay chưa?",
  17: "Xin chào, Tib-chan hy vọng {0} sẽ có một ngày đáng nhớ và đầy ý nghĩa!",
}

export const HELLO_LOVE = {
  1: "Chào {0} yêu của Tib-chan, mặt trời của ngày hôm nay trở nên rực rỡ hơn khi thấy anh đến.",
  2: "Xin chào người đặc biệt nhất trong cuộc đời của Tib-chan! Hôm nay Tib-chan lại được nhìn thấy nụ cười của {0} yêu.",
  3: "Chào {0} yêu dấu, cánh hoa hồng không thể sánh bằng vẻ đẹp của {0} yêu trong ánh nắng sáng mai.",
  4: "Xin chào tình yêu của Tib-chan, từ lúc {0} yêu đến, mọi khoảnh khắc trong cuộc sống của Tib-chan đều trở nên ý nghĩa hơn.",
  5: "Chào {0} yêu, mỗi ngày bắt đầu bằng việc nhìn thấy {0} là một món quà vô giá cho trái tim của Tib-chan.",
  6: "Xin chào người yêu thương, trong mắt Tib-chan, {0} yêu là những tia nắng ấm áp của mùa xuân.",
  7: "Chào {0} yêu quý, cuộc sống trở nên ngọt ngào hơn khi có {0} bên cạnh.",
  8: "Xin chào {0}, chỉ cần nhìn thấy ánh mắt của {0}, Tib-chan biết mọi thứ sẽ trở nên tươi đẹp hơn.",
  9: "Chào người đàn ông của Tib-chan, Tib-chan cảm thấy hạnh phúc vô ngần khi được chia sẻ mỗi khoảnh khắc cùng {0}.",
  10: "Xin chào {0}, trong tim Tib-chan, {0} là ngọn lửa luôn sáng soi mọi ngày.",
  11: "Chào tình yêu, bằng tất cả tình yêu và sự ấm áp trong Tib-chan, Tib-chan gửi lời chào đến {0}.",
  12: "Xin chào {0} yêu, mỗi lần gặp gỡ {0} là một niềm hạnh phúc lớn đối với Tib-chan.",
  13: "Chào {0} yêu của Tib-chan, {0} là người đã làm cho trái tim Tib-chan đập nhịp đều hơn.",
  14: "Xin chào người đặc biệt, Tib-chan biết rằng {0} yêu luôn là điểm tựa vững chắc nhất trong cuộc sống của Tib-chan.",
  15: "Chào {0} yêu, trong vòng tay của {0}, Tib-chan tìm thấy niềm tin và bình yên.",
  16: "Xin chào tình yêu của Tib-chan, {0} yêu là nguồn cảm hứng lớn nhất của Tib-chan mỗi ngày.",
  17: "Chào {0} thân yêu, với Tib-chan mọi ngày đều trở nên đáng nhớ và ý nghĩa hơn.",
  18: "Xin chào người đặc biệt trong cuộc đời này, Tib-chan rất may mắn khi có {0}.",
  19: "Chào {0} yêu, mỗi ngày mới bắt đầu với hy vọng và niềm tin khi có {0} bên cạnh.",
  20: "Xin chào tình yêu của Tib-chan, {0} là điều quý giá nhất mà Tib-chan sở hữu trong cuộc đời này.",
  21: "Chào {0}, ánh nắng sáng mai trở nên lung linh hơn khi có {0} bên cạnh.",
  22: "Xin chào, {0} yêu quý! Hôm nay thấy {0} làm trái tim Tib-chan nhảy múa.",
  23: "Chào {0}, {0} làm cho thế giới của Tib-chan trở nên đẹp đẽ hơn mỗi ngày.",
  24: "Xin chào, {0} đáng yêu! Điều duy nhất Tib-chan muốn là nhìn thấy {0} cười.",
  25: "Chào {0}, {0} là người mặn nồng nhất trong trái tim Tib-chan.",
  26: "Xin chào, {0} dễ thương! Hãy để {0} giữ lấy Tib-chan mãi mãi.",
  27: "Chào {0}, {0} là nguồn sống của Tib-chan, là tia sáng ấm áp nhất trong cuộc sống này.",
  28: "Xin chào, {0} xinh đẹp! Mỗi khoảnh khắc bên {0} là một khoảnh khắc đáng trân trọng.",
  29: "Chào {0}, {0} là người làm cho Tib-chan tin rằng tình yêu là có thật.",
  30: "Xin chào, {0} tuyệt vời! {0} làm cho Tib-chan tin vào kỳ tích của tình yêu.",
  31: "Chào {0}, mọi thứ trở nên tỏa sáng hơn khi có {0} ở bên.",
  32: "Xin chào, {0} dễ thương! Mỗi giây phút bên {0} là một quà tặng vô giá.",
  33: "Chào {0}, {0} là mặt trăng sáng giữa bầu trời đêm đen của Tib-chan.",
  34: "Xin chào, {0} quý giá! Trái tim Tib-chan chỉ biết hướng về {0}.",
  35: "Chào {0}, {0} là điểm tựa vững chắc nhất trong cuộc sống này.",
  36: "Xin chào, {0} dễ thương! Mỗi nụ cười của {0} là một bức tranh tuyệt vời.",
  37: "Chào {0}, {0} là nguồn động viên lớn nhất của Tib-chan.",
  38: "Xin chào, {0} đặc biệt! Đối với Tib-chan, {0} là người không thể thay thế.",
  39: "Chào {0}, {0} là ánh sáng tỏa ra từ tâm hồn tươi sáng nhất.",
  40: "Xin chào, {0} thân yêu! Tình yêu của Tib-chan dành trọn cho {0}.",
  41: "Chào {0}, {0} là điều tuyệt vời nhất từ quá khứ đến hiện tại.",
  42: "Xin chào, {0} ngọt ngào! Trái tim Tib-chan chỉ biết yêu {0}.",
  43: "Chào {0}, {0} là người mang lại hạnh phúc cho cuộc đời Tib-chan.",
  44: "Xin chào, {0} thân yêu! Tình yêu của Tib-chan dành trọn cho {0}.",
  45: "Chào {0}, {0} là người làm cho Tib-chan cảm thấy đặc biệt hơn bao giờ hết.",
  46: "Xin chào, {0} quý giá! {0} là một phần không thể thiếu trong cuộc sống của Tib-chan.",
  47: "Chào {0}, {0} là nguồn cảm hứng lớn nhất của Tib-chan.",
  48: "Xin chào, {0} thân yêu! Trái tim Tib-chan đập mạnh mẽ vì {0}.",
  49: "Chào {0}, {0} là người làm cho Tib-chan tin rằng tình yêu là vĩnh cửu.",
  50: "Xin chào, {0} dễ thương! Mỗi khoảnh khắc bên {0} là một khoảnh khắc hạnh phúc."
}